/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.boscotech.smorgasbord;

import edu.wpi.first.shuffleboard.api.plugin.Description;
import edu.wpi.first.shuffleboard.api.plugin.Plugin;

@Description(group = "edu.boscotech", name = "Smorgasbord", version = "0.0.2", 
    summary = "Adds a bunch of extra shuffleboard widgets.")
public class Smorgasbord extends Plugin {
    @Override
    public void onLoad() { }
}
